### PR TITLE
Fix creating file instance using fixture file extension

### PR DESCRIPTION
**Pull request by satrun77**
Fix for #40

### CODE REVIEW

**Review by scott1702 — APPROVED** [review]

**Comment by GuySartorelli** [comment]
This looks good overall. @satrun77 how would you feel about writing a unit test for this?

**Comment by jakxnz** [comment]
@satrun77 any chance you can get this up-to-date with tests? I've encountered the issue this solves in the wild, so would be great to have it in.

**Comment by GuySartorelli** [comment]
The broken builds for PHP < 7.4 can be ignored - I'll create a separate PR for updating the travis config for this module, but for the purposes of this PR the php 7.4 build passing is sufficient.

**Review by GuySartorelli — APPROVED** [review]
Looks good, tested locally and it works well.

I don't have access to merge this but I'll ask one of the core committers to come take a look.

**Comment by GuySartorelli** [comment]
Pinging @silverstripe/core-team to see if someone has some time to merge this in, since I don't have access to do it.

**Pull request merged**
